# This file was generated by GoReleaser. DO NOT EDIT.
cask "norn" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "7a5a842fedc5bb09f34f83f010059cbb8a0845484c33c7cd7fa1a703a26bc5bd"
      url "https://github.com/Sandbye/norn/releases/download/v#{version}/norn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "78b2a0d5c746337607f172c8172e7fd50f4a3d9eed49ff60753ddd82486e42a9"
      url "https://github.com/Sandbye/norn/releases/download/v#{version}/norn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "779080e89a41cb544db01eefe789dcefe044fcb280b2617a0665a781d21a5d85"
      url "https://github.com/Sandbye/norn/releases/download/v#{version}/norn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d2711aa3299935d6bf7bcde3062e03012f91ce1a12121458d7cff88e7d84ce6b"
      url "https://github.com/Sandbye/norn/releases/download/v#{version}/norn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "norn"
  desc "Git worktree manager TUI with per-worktree coding-agent sessions"
  homepage "https://github.com/Sandbye/norn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "norn"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/norn"]
    end
  end

  # No zap stanza required

end
