# This file was generated by GoReleaser. DO NOT EDIT.
cask "norn" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "e679a746470589d6b0b4e6db1ceddfd1ba0ec20845944250d3ed46db885a54e1"
      url "https://github.com/Sandbye/norn/releases/download/v#{version}/norn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "01e3abeca2c997ab93934ce98b4c0104c74742ad24e5a1c0a9815557353ab7a3"
      url "https://github.com/Sandbye/norn/releases/download/v#{version}/norn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c7093a617533c69b11479320fc2f2315705752a7f4b604208a49dabebc3170c8"
      url "https://github.com/Sandbye/norn/releases/download/v#{version}/norn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d03b87af7b77b9e3b405221a06c917f17fa28e707e2a820398ddf8b12047c5db"
      url "https://github.com/Sandbye/norn/releases/download/v#{version}/norn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "norn"
  desc "Git worktree manager TUI with per-worktree coding-agent sessions"
  homepage "https://github.com/Sandbye/norn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "norn"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/norn"]
    end
  end

  # No zap stanza required

end
