# This file was generated by GoReleaser. DO NOT EDIT.
cask "norn" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "762bf60c8041f7261c3ff4115c371a5f6a2c05cc375321f691961a4212e00f5b"
      url "https://github.com/Sandbye/norn/releases/download/v#{version}/norn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2a4bdde35f9018b49e6ebf9b4ef6acb79ba9874d2d65cf7908ad010fb45bd0d9"
      url "https://github.com/Sandbye/norn/releases/download/v#{version}/norn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "af965eb55ace71d289209914c176950812d62f905aa420c118db048763ac273a"
      url "https://github.com/Sandbye/norn/releases/download/v#{version}/norn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "602f8f8a296db7dfdac75b0a27bdad934e28f17223de9f4ccdea6d15d2d0e70d"
      url "https://github.com/Sandbye/norn/releases/download/v#{version}/norn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "norn"
  desc "Git worktree manager TUI with per-worktree coding-agent sessions"
  homepage "https://github.com/Sandbye/norn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "norn"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/norn"]
    end
  end

  # No zap stanza required

end
